#!/bin/bash

# Compile the Java source file
javac -cp "../jars/junit-jupiter-api-5.8.2.jar:../jars/apiguardian-api-1.1.2.jar" VestingProgram_Stage3.java VestingProgramTest.java TestUtils.java 

# Check if compilation was successful before running the program
if [ $? -eq 0 ]; then
    # Execute the compiled Java program
    java -jar ../jars/junit-platform-console-standalone-1.8.2.jar --class-path . --scan-classpath
else
    echo "Compilation failed. Please check the Java source file for errors."
fi

